### ISSUE TITLE
Running the get_node_groups function inside a plan via PE console produces error

### ISSUE THREAD

**Issue by tuxmea** [betadots/puppet-bolt_pe#2]
Running the get_node_groups plan via PE console causes an error, because the function is executed as pe-orchestration-services user and not as root:

```
Plan output

{
  "msg" : "No such file or directory - /opt/puppetlabs/server/data/orchestration-services/.puppetlabs/etc/puppet/ssl/certs/puppet5.dtt.example42.training.pem",
  "kind" : "bolt/plan-failure",
  "details" : {
    "class" : "Bolt::PAL::PALError"
  }
}
```

I am unsure if we should switch to a task instead.
@rwaffen any ideas?

**Comment by rwaffen** [comment]
ja i saw that to. the error is, that the orchestrator user executes the puppet print command and returns wrong/non-existant *.pem pathes for the conncection to puppet db.

**Comment by rwaffen** [comment]
is it supposed to be executed in the orchestrator? i thought it would only be run by bolt?

**Comment by tuxmea** [comment]
When functions are run by the orchestrator, they are run by the orchestrator user. Not root.
We should convert this to a task and check that the task is run as root user and on the PE Primary Server.
